[package]
name = "lupine-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI for the Lupine PQC suite"

[[bin]]
name = "lupine"
path = "src/main.rs"

[dependencies]
lupine = { path = "../lupine" }
lupine-core = { workspace = true }
lupine-kem = { workspace = true }
lupine-sign = { workspace = true }
lupine-serial = { workspace = true }
ml-kem = { workspace = true }
ml-dsa = { workspace = true }
slh-dsa = { workspace = true }
clap = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
rand_010 = { package = "rand", version = "=0.10.0" }
rand_core_010 = { package = "rand_core", version = "=0.10.0" }
anyhow = { workspace = true }
